version: '3.7'
services:
  pg:
    image: bitnami/postgresql
    ports:
      - '5434:5432'
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: crmagenda
    volumes:
      - ./data:/var/lib/postgresql/data
